# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00a6d907dfeedfac965d01484b32308e4d5a42c1463f1359284a5e7cc18ea31b402a044f91cd6fa6011fcb8bb6bc1946f073b35e1f831db5b2838df7dac85b15

test:
  secret_key_base: 7ecbc50c53b6e8321c9340b0fd2dc05c26b568423c328c1fb2e71e164c8d624b4145ec1bfa7bf0fc3ea1827599fe149bc5176d4cd0d37e5378f0b87d191b239b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
